### PR TITLE
Upgrade to mima 0.1.15 & workaround sbt 0.13.16 bug

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
@eed3si9n wdyt?

**Comment by eed3si9n** [comment]
I guess it's fine, but we should contribute this to upstream so we don't diverge too much.

**Comment by dwijnand** [comment]
Happy to.

**Comment by dwijnand** [comment]
Actually, reviewing the changes (https://github.com/mdedetrich/scalajson/compare/master...eed3si9n:1.0.0-M4-fork) there's not a lot to contribute as the official library isn't guaranteeing any binary compatibility.

But as soon as they do I'll be sure to push these changes their way.

**Comment by eed3si9n** [comment]
> there's not a lot to contribute as the official library isn't guaranteeing any binary compatibility.

Doh. You're right.

**Pull request merged**
